### ISSUE TITLE
Order of Numpy Random calls in Exercise 2.2

### ISSUE THREAD

**Issue by ymahlau** [automl-classroom/iML-ws21-ex05#1]
Hello,

Could you give some more details about the order of np.random calls in Exercise 2.2? Should we first sample all points z by calling 
`[X[i] for i in np.random.choice(len(X), M)]` (another option would be `[X[np.random.choice(len(x))] for _ in range(M)]`  which changes the RNG) and then iteratively call the permutations `np.random.permutation(len(x))` in a for-loop? Or should we sample one point and  one permutation in an alternating way? If so, should we first sample z or the permutation? All of these factors change the random number generation and therefore the test result.

I think my implementation still has some other errors since the test failed with all possible combinations mentioned above. However, it is very difficult to debug the code if I don't know which of the mentioned possibilities is the correct one. Could you give some more insights about the correct order of calls to the np.random-functions?

Thanks in Advance!
Yannik

**Comment by renesass** [comment]
```
idx for np.random.choice(len(X), M):
    ....
    pi = np.random.permutation(len(x))
    ....
```

**Comment by ymahlau** [comment]
Thank you!
