### ISSUE TITLE
Possible Error in Test Case for check_additivity? 

### ISSUE THREAD

**Issue by ymahlau** [automl-classroom/iML-ws21-ex05#2]
Hello,

I believe there may be an error in the last assertion of the check_additivity test:
`def v(S): return get_value(S, COMB13)`
`def v1(S): return get_value(S, COMB14)`
`def v2(S): return get_value(S, COMB15)`
`assert module.check_additivity(S, 2, v, v1, v2)`

However, when calculating the additivity, we have to check for all subsets of S, which are {{}, {1}, {3}, {1,3}}. For S'={3} and j = 2 we get the value 67-25=42 on the left side and 24-15+25-10=24 on the right side of equation (6) in the exercise sheet. Therefore this contribution is not additive and the assertion should be false.

Do I make a mistake in my calculation or is a negation in missing in the test case?

Thanks Yannik

**Comment by renesass** [comment]
Yup. You are right. Please change COMB13[(2, 3)] = 49 in `datasets/shapley.py`.
Thank you!
