### ISSUE TITLE
Task 2.2: Please specify when to use random.

### ISSUE THREAD

**Issue by tschoon** [automl-classroom/iML-ws21-ex05#3]
https://github.com/automl-classroom/iML-ws21-ex05/blob/2bbdeb1459055fa2588644182d14be70ecf0864d/tasks/model_agnostic.py#L43

Hello,
because of the side effects of  calling the np.random.*() method it is important to know when you have to call it in order to receive the right choice/permutation. After many tries we solved the exercise according to the test cases...
It would be very helpful if you could explain a bit more **when** we should use random, because there are many possibilities to solve the exercise but only a few that matches the test cases.
A simple "solution" could be to reset the seed after every call of random.
Another solution could be to specify how often we should use random inside of the for loop and in other places...
Best regards
Jatoca

**Comment by renesass** [comment]
https://github.com/automl-classroom/iML-ws21-ex05/issues/1
