### ISSUE TITLE
Task 1.2: Test_by_order_approx

### ISSUE THREAD

**Issue by m-kruse98** [automl-classroom/iML-ws21-ex05#4]
As I understood it, in the test case test_get_shapley_by_order_approx we execute our function twice, only with different M values. M determines how many times we execute our algorithm. Each time we execute it, the sum should become larger (I tried to verify it for the given v and j).

Why exactly do the tests demand that the solution for M = 10 is larger than for M = 24. I am still failing this test. Am I missing something?

**Comment by renesass** [comment]
The solution with M = 10 is not as accurate as with M = 24. And no, you don't execute your function twice. With less M you just iterate less.
