### ISSUE TITLE
Task 2.2 

### ISSUE THREAD

**Issue by rhotertj** [automl-classroom/iML-ws21-ex05#5]
Task: _"Sample random instances z in X using np.random.choice and iterate over them. Use then np.random.permutation to get a permutation order for both given point x and random instance z. Those two steps are important to ensure correct testing."_

The task says that we should sample random instances and iterate over them.
We think this would suggest using `for i in np.random.choice(X.shape[0], size=M):` but the tests will fail.
The tests pass if you iterate over M and alternate sampling and permutating, so you might want to clarify that :)

**Comment by renesass** [comment]
https://github.com/automl-classroom/iML-ws21-ex05/issues/1

**Comment by rhotertj** [comment]
My bad, did not check the closed issues ;)
