### ISSUE TITLE
Task 1.2: Better understanding

### ISSUE THREAD

**Issue by felixmeyjr** [automl-classroom/iML-ws21-ex05#8]
I dont really have understood, what exactly 𝑃𝑟𝑒(𝜏, 𝑗) ∪ {𝑗}) is? Let's say we have like in the first test case for 1.2 four players. This implies that capital PI has the length of |P|!, which is 24, meaning all possible combinations of (1,2,3,4). 

When we sum up over all taos of capital pi (in total 24 "taos") and with j being 4, 𝑃𝑟𝑒(𝜏, 𝑗) can only be {1,2,3} because sets are unordered, right? This will also imply that 𝑃𝑟𝑒(𝜏, 𝑗) ∪ {𝑗} will always be {1,2,3,4}, because again _everything is unsorted._ 

In COMB10, for (1, 2, 3) the payout is 52 and for (1,2,3,4) 100, respectively. So in the end we add 100-52 (v(Pre(τ,j) ∪{j}) −v(Pre(τ,j))) 24 times (with M=None) to the value and divide by |P|! (=24). What am I missing, because this does not result in a correct test.

Thanks in advance
BR

**Comment by renesass** [comment]
The position of j indeed matters in Pre as you always take the players before j was inserted.
